wazuh_full_version: "5.0.0"
wazuh_major_minor_version: "5.0"
wazuh_major_version: "5.x"
wazuh_package_revision: "1"

local_configs_path: "{{ playbook_dir }}/deployment-config-files"

urls_file: "artifacts_urls.yml"
