---

- name: Linux Debian (AMD64) | Download wazuh-agent package
  get_url:
    url: "{{ wazuh_agent_url_amd64_deb }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}"
  when:
    - ansible_os_family|lower != "redhat"
    - ansible_architecture == "x86_64"

- name: Linux Debian (ARM64) | Download wazuh-agent package
  get_url:
    url: "{{ wazuh_agent_url_arm64_deb }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}"
  when:
    - ansible_os_family|lower != "redhat"
    - ansible_architecture == "aarch64"
