---

- name: Linux | Create directory for wazuh-agent package
  ansible.builtin.file:
    path: "{{ wazuh_agent_package_download_path }}"
    state: directory
    mode: '0755'

# Download package tasks

- include_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- include_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

# Installation tasks

- name: Linux | Create file for storing Wazuh Server IPs in environment variable(s)
  ansible.builtin.copy:
    dest: "{{ wazuh_agent_package_download_path }}/wazuh-agent-addresses"
    content: ""
    mode: '0644'

- name: Linux | Handle Wazuh Server IPs
  block:
    - name: Linux | Create environment variable for Wazuh Server IP [1/3] (Cluster failover mode)
      ansible.builtin.lineinfile:
        path: "{{ wazuh_agent_package_download_path }}/wazuh-agent-addresses"
        line: "WAZUH_MANAGER=\"{{ wazuh_server_addresses | join(',') }}\""
        create: yes
        state: present
      when: wazuh_server_addresses | length > 1

    - name: Linux | Create environment variable for Wazuh Server IP [2/3] (Cluster failover mode)
      ansible.builtin.lineinfile:
        path: "{{ wazuh_agent_package_download_path }}/wazuh-agent-addresses"
        line: "WAZUH_REGISTRATION_SERVER=\"{{ wazuh_server_addresses[0] }}\""
        create: yes
        state: present
      when: wazuh_server_addresses | length > 1

    - name: Linux | Create environment variable for Wazuh Server IP [3/3] (Single server mode)
      ansible.builtin.lineinfile:
        path: "{{ wazuh_agent_package_download_path }}/wazuh-agent-addresses"
        line: "WAZUH_MANAGER=\"{{ wazuh_server_addresses[0] }}\""
        create: yes
        state: present
      when: wazuh_server_addresses | length == 1

- name: Reload environment variables
  shell: |
    source {{ wazuh_agent_package_download_path }}/wazuh-agent-addresses
  args:
    executable: /bin/bash

- name: Linux CentOS/RedHat | Install wazuh-agent using yum
  yum:
    name: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_os_family|lower == "redhat"

- name: Linux Debian | Install wazuh-agent using dpkg
  shell: |
    dpkg -i {{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}
  when:
    - ansible_os_family|lower != "redhat"

- name: Linux | Start and enable Wazuh Agent service
  block:
    - name: Linux | Reload systemd daemon
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Linux | Ensure Wazuh Agent service is stopped [1/3]
      service:
        name: wazuh-agent
        state: stopped
      ignore_errors: yes

    - name: Linux | Ensure Wazuh Agent service is disabled [2/3]
      service:
        name: wazuh-agent
        enabled: false
      ignore_errors: yes

    - name: Linux | Ensure Wazuh Agent service is started and enabled [3/3]
      service:
        name: wazuh-agent
        enabled: true
        state: started

- name: Linux | Remove leftover wazuh-agent installation directory
  ansible.builtin.file:
    path: "{{ wazuh_agent_package_download_path }}"
    state: absent
    recurse: yes
