---

- name: MacOS | Create directory for Wazuh agent package
  ansible.builtin.file:
    path: "{{ wazuh_agent_package_download_path }}"
    state: directory
    mode: '0755'

- name: MacOS (Intel) | Download Wazuh agent package
  get_url:
    url: "{{ wazuh_agent_url_amd64_macos }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg"
  when:
    - ansible_architecture == "x86_64"

- name: MacOS (ARM) | Download Wazuh agent package
  get_url:
    url: "{{ wazuh_agent_url_arm64_macos }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg"
  when:
    - ansible_architecture == "aarch64"

- name: MacOS | Set deployment variables for Wazuh agent enrollment
  block:
    - name: MacOS | Ensure file for storing deployment variable(s) exists
      ansible.builtin.file:
        path: "/tmp/wazuh_envs"
        state: touch
        mode: '0644'

    - name: MacOS | Set deployment variables for Wazuh agent enrollment (Cluster failover mode)
      ansible.builtin.lineinfile:
        path: "/tmp/wazuh_envs"
        line: "WAZUH_MANAGER='{{ wazuh_server_addresses | join(',') }}' && WAZUH_REGISTRATION_SERVER='{{ wazuh_server_addresses[0] }}'"
        create: yes
        state: present
      when: wazuh_server_addresses | length > 1

    - name: MacOS | Set deployment variables for Wazuh agent enrollment (Single server mode)
      ansible.builtin.lineinfile:
        path: "/tmp/wazuh_envs"
        line: "WAZUH_MANAGER='{{ wazuh_server_addresses[0] }}'"
        create: yes
        state: present
      when: wazuh_server_addresses | length == 1

- name: MacOS | Install Wazuh agent using installer
  command: "installer -pkg {{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg -target /"

- name: MacOS | Initialize Wazuh agent service
  command: "launchctl load /Library/LaunchDaemons/com.wazuh.agent.plist"

- name: MacOS | Pause for 10 seconds while Wazuh agent service initializes
  pause:
    seconds: 10

- name: MacOS | Verify Wazuh agent service is running
  shell: "launchctl list | grep com.wazuh.agent"
  register: wazuh_agent_service_status
  failed_when: "'com.wazuh.agent' not in wazuh_agent_service_status.stdout"
  changed_when: false
