---

- name: MacOS | Create directory for Wazuh agent package
  ansible.builtin.file:
    path: "{{ wazuh_agent_package_download_path }}"
    state: directory
    mode: '0755'

- name: MacOS (Intel) | Download Wazuh agent package
  get_url:
    url: "{{ wazuh_agent_url_amd64_macos }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg"
  when:
    - ansible_architecture == "x86_64"

- name: MacOS (ARM) | Download Wazuh agent package
  get_url:
    url: "{{ wazuh_agent_url_arm64_macos }}"
    dest: "{{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg"
  when:
    - ansible_architecture == "aarch64"

- name: MacOS | Install Wazuh agent using installer
  command: "installer -pkg {{ wazuh_agent_package_download_path }}/{{ wazuh_agent_package_name }}.pkg -target /"

- name: MacOS | Initialize Wazuh agent service (MacOS 10.10+)
  command: "launchctl bootstrap system /Library/LaunchDaemons/com.wazuh.agent.plist"
  when: ansible_distribution_version is version('10.10', '>=')

- name: MacOS | Load Wazuh agent service (MacOS < 10.10)
  command: "launchctl load /Library/LaunchDaemons/com.wazuh.agent.plist"
  when: ansible_distribution_version is version('10.10', '<')

- name: Update Wazuh agent configuration with Wazuh server IP address
  become: yes
  lineinfile:
    path: "/Library/Application Support/Wazuh agent.app/etc/wazuh-agent.yml"
    regexp: '^  server_url: https://.*:27000'
    line: '  server_url: https://{{ wazuh_server_addresses[0] }}:27000'
    state: present

- name: MacOS | Register Wazuh agent
  command: "/Library/Application\\ Support/Wazuh\\ agent.app/bin/wazuh-agent --register-agent --user wazuh --password wazuh --url https://{{ wazuh_server_addresses[0] }}:55000 --verification-mode none"

- name: MacOS | Restart Wazuh agent service (MacOS 10.10+)
  command: "launchctl kickstart -k system/com.wazuh.agent"
  when: ansible_distribution_version is version('10.10', '>=')

- name: MacOS | Restart Wazuh agent service (MacOS < 10.10)
  command: "launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist && launchctl load /Library/LaunchDaemons/com.wazuh.agent.plist"
  when: ansible_distribution_version is version('10.10', '<')

- name: MacOS | Pause for 5 seconds while Wazuh agent service initializes
  pause:
    seconds: 5

- name: MacOS | Verify Wazuh agent service is running
  shell: "launchctl list | grep com.wazuh.agent"
  register: wazuh_agent_service_status
  failed_when: "'com.wazuh.agent' not in wazuh_agent_service_status.stdout"
  changed_when: false
