---

- include_vars: ../../vars/main.yml

- include_vars: ../../vars/{{ urls_file }}

- include_tasks: "Linux.yml"
  when: ansible_system == "Linux"

- include_tasks: "Windows.yml"
  when: ansible_os_family == "Windows"

- include_tasks: "macOS.yml"
  when: ansible_system == "Darwin"
