---

- name: Importing variables [vars/main.yml]
  ansible.builtin.include_vars:
    file: ../../vars/main.yml

- name: Importing urls_file variables
  ansible.builtin.include_vars:
    file: ../../vars/{{ urls_file }}

- name: Linux | Importing tasks for Linux systems
  ansible.builtin.include_tasks:
    file: "Linux.yml"
  when: ansible_facts.system == "Linux"

- name: Windows | Importing tasks for Windows systems
  ansible.builtin.include_tasks:
    file: "Windows.yml"
  when: ansible_facts.os_family == "Windows"

- name: MacOS | Importing tasks for macOS systems
  ansible.builtin.include_tasks:
    file: "macOS.yml"
  when: ansible_facts.system == "Darwin"
