---

- name: Windows | Ensure Wazuh agent download directory exists
  win_file:
    path: "{{ wazuh_agent_win_package_download_path }}"
    state: directory

- name: Windows | Download Wazuh agent installer
  win_get_url:
    url: "{{ wazuh_agent_url_win }}"
    dest: "{{ wazuh_agent_win_package_download_path }}\\{{ wazuh_agent_package_name }}.msi"

- name: Windows | Install Wazuh agent (Single server mode)
  win_package:
    path: "{{ wazuh_agent_win_package_download_path }}\\{{ wazuh_agent_package_name }}.msi"
    arguments: '/q WAZUH_MANAGER="{{ wazuh_server_addresses[0] }}"'
    state: present
  when: wazuh_server_addresses | length == 1

- name: Windows | Install Wazuh agent (Cluster failover mode)
  win_package:
    path: "{{ wazuh_agent_win_package_download_path }}\\{{ wazuh_agent_package_name }}.msi"
    arguments: "/q WAZUH_MANAGER=\"{{ wazuh_server_addresses | join(',') }}\" WAZUH_REGISTRATION_SERVER=\"{{ wazuh_server_addresses[0] }}\""
    state: present
  when: wazuh_server_addresses | length > 1

- name: Windows | Start Wazuh agent service
  win_service:
    name: Wazuh
    start_mode: auto
    state: started

- name: Windows | Delete Wazuh agent download directory
  win_file:
    path: "{{ wazuh_agent_win_package_download_path }}"
    state: absent
