---

- name: Ensure wazuh-indexer package download directory exists
  file:
    path: "{{ wazuh_indexer_package_download_path }}"
    state: directory
    mode: '0755'

- name: Amazon Linux | Configure system settings
  block:
    - name: Amazon Linux | Install Amazon extras in Amazon Linux 2
      yum:
        name: amazon-linux-extras
        state: present
      when:
        - ansible_facts.distribution_major_version == '2'

    - name: Amazon Linux | Configure vm.max_map_count
      lineinfile:
        line: "vm.max_map_count=262144"
        dest: "/etc/sysctl.conf"
        insertafter: EOF
        create: true
      become: yes

    - name: Amazon Linux | Update vm.max_map_count
      shell: sysctl -p
      become: yes
  when:
    - ansible_facts.os_family == 'Amazon'

- name: RHEL, CentOS, and Amazon Linux 2 | Configure system settings and install dependencies
  block:
    - name: RedHat/CentOS/Fedora | Install Indexer dependencies
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - coreutils
        - wget
        - unzip

    - name: RedHat/CentOS/Fedora (x86_64) | Download wazuh-indexer package
      get_url:
        url: "{{ wazuh_indexer_url_amd64_rpm }}"
        dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}_{{ ansible_facts.architecture }}.rpm"
      when:
        - ansible_facts.architecture == "x86_64"

    - name: RedHat/CentOS/Fedora (aarch64) | Download wazuh-indexer package
      get_url:
        url: "{{ wazuh_indexer_url_arm64_rpm }}"
        dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}_{{ ansible_facts.architecture }}.rpm"
      when:
        - ansible_facts.architecture == "aarch64"
  when:
    - ansible_facts.os_family == 'RedHat'

- name: Debian-based systems | Install Wazuh indexer dependencies and download package
  block:
    - name: Debian-based | Install Indexer dependencies
      apt:
        name:
          - 'debconf'
          - 'adduser'
          - 'procps'
        state: present

    - name: Debian-based (AMD64) | Download wazuh-indexer package
      get_url:
        url: "{{ wazuh_indexer_url_amd64_deb }}"
        dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}_{{ ansible_facts.architecture }}.deb"
      when:
        - ansible_facts.architecture == "x86_64"

    - name: Debian-based (ARM64) | Download wazuh-indexer package
      get_url:
        url: "{{ wazuh_indexer_url_arm64_deb }}"
        dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}_{{ ansible_facts.architecture }}.deb"
      when:
        - ansible_facts.architecture == "aarch64"
  when:
    - ansible_facts.os_family == 'Debian'
