---

single_node: false
instances:
  wi1:
    name: node-1
    ip: '{{ hostvars.wi1.private_ip }}'
    role: indexer

generate_certs: true
local_configs_path: "{{ playbook_dir }}/indexer-config"

wazuh_indexer_package_download_path: "/tmp/wazuh-indexer"
wazuh_indexer_package_name: "wazuh-indexer-package"
