---

single_node: false
instances:
  wi1:
    name: node-1
    ip: '{{ hostvars.wi1.private_ip }}'
    role: indexer

generate_certs: true

wazuh_indexer_package_download_path: "/tmp/wazuh-indexer"
wazuh_indexer_package_name: "wazuh-indexer-{{ wazuh_full_version }}-{{ wazuh_package_revision }}"
